[theme]
base="dark"
primaryColor="#00E5FF"
backgroundColor="#0B0F1A"
secondaryBackgroundColor="#121A2B"
textColor="#FFFFFF"

[server]
headless=true

[supabase]
url = "TU_URL"
service_role_key = "TU_SERVICE_ROLE"

[admin]
password = "TU_PASSWORD_ADMIN"

[resend]
api_key = "TU_API_KEY"
from_email = "onboarding@resend.dev"